In this script, we conduct ensemble learning based on the analyses of each single model's confusion matrix and performance. After 1. Averaging ensemble; 2. Conditional ensemble; 3. Weighted ensemble, we produced an "All results" table. We also tried 4. Subdistrict conditional ensemble, but did not consider it.


##### 1. Averaging ensemble

We tried 7 averaging ensembled models: 

- all single models; 

- models with best accuracy (cv2cv4, cv2cv4full);

- models best at predicting target 0 (cv2cv3full, cv3full);

- models best at predicting target 1(cv1cv0cv4, cv1cv0).

Averaging ensembled models' results showed that model 'cv3full' was best at predicting safety = 0 and model 'cv0cv1cv4' was best at predicting safety = 1. We would use these 2 models in conditional and weighted ensemble.

##### 2. Conditional ensemble

'Conditional ensemble1': When predicting safety = 0, we use the prediction by 'cv3full'; else we use the prediction by 'cv0cv1cv4'.

'Conditional ensemble2': When predicting safety = 1, we use the prediction by 'cv0cv1cv4'; else we use the prediction by 'cv3full'.

These two models are good at predicting only one of the targets each. Therefore we looked at weighted ensemble.

##### 3. Weighted ensemble

'weighted ensemble1': We give prediction by model 'cv3full' 0.4 weight; and prediction by model 'cv0cv1cv4' 0.6 weight.

'weighted ensemble2': We give prediction by model 'cv3full' 0.45 weight; and prediction by model 'cv0cv1cv4' 0.55 weight.

'weighted ensemble3': We give prediction by model 'cv3full' 0.55 weight; and prediction by model 'cv0cv1cv4' 0.45 weight.

'Weighted ensemble 4': We give prediction by model 'cv3full' 0.555 weight; and prediction by model 'cv0cv1cv4' 0.455 weight.


##### 4. Subdistrict conditional ensemble

We analyzed the confusion matrix by subdistrict, and tried one ensembled model based on the sigle model's performance by subdistrict. This model's performance was not better than the best model produced during 1,2,3. Also considering the subdistrict is not a feature in neural networks of the images, we would not consider this model.


##### Conclusion
Examining the "All results" table, we found that the ensembled model of 'all models' would produce the best accuracy. However, it is better at predicting safety = 1 than predicting safety = 0. 

Model 'Weighted ensemble 4' is the second best, and it is good at predicting both safety = 0 and safety = 1. Therefore, we would consider 'Weighted ensemble 4' as our final model.

In [136]:
import pandas as pd
import numpy as np
import glob
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

### Before ensembling: single model accuracy

Six models (best models produced from cv0, cv1, cv2, cv3, cv4 and whole training dataset) were produced in the transfer learning process. Validation accuracy showed that the models' accuracy was around 70%. Later we would show that averaging ensemble could lift the accuracy.

In [235]:
cv_score = pd.read_pickle("/Users/zhanglingling/Desktop/ML1030/boston_train_evaluate/cv_score.pickle")
cv_score

CV round,0,1,2,3,4,mean,std
train_loss,0.167847,0.070979,0.085303,0.051624,0.052649,0.085680,0.042939
train_acc,0.947100,0.972844,0.970884,0.980929,0.979752,0.970302,0.012226
val_loss,1.802394,1.540489,1.852702,1.808886,1.562203,1.713335,0.133567
val_acc,0.669805,0.672003,0.691994,0.672214,0.692622,0.679727,0.010308

In [236]:
wholedata_score = pd.read_pickle("/Users/zhanglingling/Desktop/ML1030/boston_train_evaluate/wholedata_score.pickle")
wholedata_score

       loss       acc
0  0.058055  0.978464

We calculate the confusion matrix of each single model

In [806]:
predict_dir = '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/'
file_list = list(glob.glob(predict_dir + "*.csv*"))
file_list.sort()
file_list

['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv0.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv1.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv2.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv3.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv4.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.wholedata.hdf5.prediction.csv']

In [807]:
df_list = []
for f in file_list:
    df = pd.read_csv(f)
    df = df.sort_values("_file")
    df_list.append(df)

In [808]:
test_csv = "/Users/zhanglingling/Desktop/ML1030/us_safety/boston_test_fetched_with_target.csv"  
test_df = pd.read_csv(test_csv)
test_df = test_df.sort_values("_file")
target = "safety"
img_name_col = "_file"
test_df = test_df[[img_name_col, target]]
print(test_df.shape)
print(averaged_prediction.shape)
test_df.head()

(3976, 2)
(3975, 4)

            _file  safety
0       gsv_0.jpg       1
1       gsv_1.jpg       1
10     gsv_10.jpg       0
99    gsv_100.jpg       1
992  gsv_1000.jpg       1

Note that test_df have 3976 samples whereas all my predictions have 3975 samples, that is because one image was not able to be fetched by the Google Street View API. Below is just using CV0's prediction to try.

In [809]:
df = pd.merge(test_df, df_list[0], how='left', on='_file', 
                   indicator=True)
df[df['_merge'] == 'left_only']

            _file  safety   0   1     _merge
640  gsv_1578.jpg       0 NaN NaN  left_only

Removing the one sample with unfetched image, we found in test set we have 2153 actual safety = 0 and 1822 actual safety =1

In [810]:
df = df[df['_merge'] == 'both']
df.groupby(['safety']).count()

        _file     0     1  _merge
safety
0        2153  2153  2153    2153
1        1822  1822  1822    1822

In [815]:
# function that calculates each single model's confusion matrix and performance tables
def matrix_performance_singlemodel(test_df, data):
    
    #for a single model, no need to average
    prediction = data 
    prediction['pred_safety'] =  np.where(prediction['0'] > 0.5, 0, 1)
    
    #prepare y_true, y_pred
    df = pd.merge(test_df, prediction, how='left', on='_file', 
                   indicator=True)
    df[df['_merge'] == 'left_only']
    df = df[df['_merge'] == 'both']
    df['pred_safety'] = df['pred_safety'].astype(int)
    
    y_true = df['safety']
    y_pred = df['pred_safety']
    
    #confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    matrix = pd.DataFrame([{'tn': tn, 'fp': fp, 'fn': fn, 'tp': tp}])
    matrix['tn_rate'] = matrix['tn'] / (matrix['tn'] + matrix['fp'])
    matrix['tp_rate'] = matrix['tp'] / (matrix['fn'] + matrix['tp'])
    

    matrix['fp_rate'] = matrix['fp'] / (matrix['tn'] + matrix['fp'])
    matrix['fn_rate'] = matrix['fn'] / (matrix['fn'] + matrix['tp'])
    
    
    #performance
    accuracy = accuracy_score(y_true, y_pred) # accuracy: (tp + tn) / (p + n)
    precision = precision_score(y_true, y_pred) # precision tp / (tp + fp)
    recall = recall_score(y_true, y_pred) # recall: tp / (tp + fn)
    f1 = f1_score(y_true, y_pred) # f1: 2 tp / (2 tp + fp + fn)
    performance = pd.DataFrame([{'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 score': f1}])
    
    return matrix, performance

In [816]:
conf_matrix_table = pd.DataFrame(columns=['fn','fp','tn', 'tp', 'tn_rate', 'tp_rate', 'fp_rate', 'fn_rate'])
performance_table = pd.DataFrame(columns=['Accuracy', 'F1 score', 'Precision', 'Recall'])

for i in range(len(df_list)):
    conf_matrix, performance = matrix_performance_singlemodel(test_df, df_list[i])
    conf_matrix_table = pd.concat([conf_matrix_table, conf_matrix])
    performance_table = pd.concat([performance_table, performance])

conf_matrix_table['model'] = ['cv0', 'cv1', 'cv2', 'cv3', 'cv4', 'full']
performance_table['model'] = ['cv0', 'cv1', 'cv2', 'cv3', 'cv4', 'full']

In [817]:
performance_table

   Accuracy  F1 score  Precision    Recall  model
0  0.700881  0.692208   0.655071  0.733809    cv0
0  0.693836  0.693990   0.640371  0.757409    cv1
0  0.701635  0.684239   0.664426  0.705269    cv2
0  0.695346  0.658777   0.676896  0.641603    cv3
0  0.700881  0.688988   0.658171  0.722832    cv4
0  0.719497  0.690364   0.698707  0.682217  whole

In [818]:
conf_matrix_table

    fn   fp    tn    tp   tn_rate   tp_rate   fp_rate   fn_rate  model
0  485  704  1449  1337  0.673014  0.733809  0.326986  0.266191    cv0
0  442  775  1378  1380  0.640037  0.757409  0.359963  0.242591    cv1
0  537  649  1504  1285  0.698560  0.705269  0.301440  0.294731    cv2
0  653  558  1595  1169  0.740827  0.641603  0.259173  0.358397    cv3
0  505  684  1469  1317  0.682304  0.722832  0.317696  0.277168    cv4
0  579  536  1617  1243  0.751045  0.682217  0.248955  0.317783  whole

From above results, we can see that for the 6 single models:

Three models - whole, cv3, cv2 are better than the others in predicting 0;

Three models - cv1, cv0, cv4 are better than the others in predicting 1

## 1. Averaging ensemble
### 1.1 Averaging ensemble of all single models

In [819]:
# function that calculates averging ensemble model's confusion matrix and performance tables
def matrix_performance(test_df, file_list):
    
    #produce averaging ensembled model's prediction - 'averaged_prediction'
    df_list = []
    for f in file_list:
        df = pd.read_csv(f)
        df = df.sort_values("_file")
        df_list.append(df)
        
    averaged_prediction = pd.concat(df_list).groupby('_file').mean()
    averaged_prediction.reset_index(level=0, inplace=True)
    averaged_prediction['pred_safety'] =  np.where(averaged_prediction['0'] > 0.5, 0, 1)
    
    #prepare y_true, y_pred
    df = pd.merge(test_df, averaged_prediction, how='left', on='_file', 
                   indicator=True)
    df[df['_merge'] == 'left_only']
    df = df[df['_merge'] == 'both']
    df['pred_safety'] = df['pred_safety'].astype(int)
    
    
    y_true = df['safety']
    y_pred = df['pred_safety']
    
    #confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    matrix = pd.DataFrame([{'tn': tn, 'fp': fp, 'fn': fn, 'tp': tp}])
    
    matrix['tn_rate'] = matrix['tn'] / (matrix['tn'] + matrix['fp'])
    matrix['tp_rate'] = matrix['tp'] / (matrix['fn'] + matrix['tp'])
    
    matrix['fp_rate'] = matrix['fp'] / (matrix['tn'] + matrix['fp'])
    matrix['fn_rate'] = matrix['fn'] / (matrix['fn'] + matrix['tp'])
    
    #performance
    accuracy = accuracy_score(y_true, y_pred) # accuracy: (tp + tn) / (p + n)
    precision = precision_score(y_true, y_pred) # precision tp / (tp + fp)
    recall = recall_score(y_true, y_pred) # recall: tp / (tp + fn)
    f1 = f1_score(y_true, y_pred) # f1: 2 tp / (2 tp + fp + fn)
    performance = pd.DataFrame([{'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 score': f1}])
    
    return matrix, performance

In [820]:
predict_dir = '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/'
file_list = list(glob.glob(predict_dir + "*.csv*"))
file_list.sort()
file_list

['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv0.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv1.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv2.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv3.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv4.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.wholedata.hdf5.prediction.csv']

In [821]:
conf_matrix_all, performance_all = matrix_performance(test_df, file_list)
conf_matrix_all['model'] = ['all models']
performance_all['model'] = ['all models']
display(conf_matrix_all, performance_all)

    fn   fp    tn    tp   tn_rate   tp_rate   fp_rate   fn_rate       model
0  440  606  1547  1382  0.718532  0.758507  0.281468  0.241493  all models

   Accuracy  F1 score  Precision    Recall       model
0  0.736855  0.725459   0.695171  0.758507  all models

### 1.2 Averaging ensemble of models with best accuracy only (cv2, cv4)

In [822]:
file_list = ['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv2.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv4.prediction.csv']
conf_matrix_cv2cv4, performance_cv2cv4 = matrix_performance(test_df, file_list)
conf_matrix_cv2cv4['model'] = ['cv2cv4']
performance_cv2cv4['model'] = ['cv2cv4']
display(conf_matrix_cv2cv4, performance_cv2cv4)

    fn   fp    tn    tp   tn_rate   tp_rate   fp_rate   fn_rate   model
0  472  653  1500  1350  0.696702  0.740944  0.303298  0.259056  cv2cv4

   Accuracy  F1 score  Precision    Recall   model
0  0.716981  0.705882   0.673989  0.740944  cv2cv4

### 1.3 Averaging ensemble of models withs best accuracy only (cv2, cv4, full)

In [823]:
file_list = ['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv2.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv4.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.wholedata.hdf5.prediction.csv']
conf_matrix_cv2cv4full, performance_cv2cv4full = matrix_performance(test_df, file_list)
conf_matrix_cv2cv4full['model'] = ['cv2cv4full']
performance_cv2cv4full['model'] = ['cv2cv4full']
display(conf_matrix_cv2cv4full, performance_cv2cv4full)

    fn   fp    tn    tp  tn_rate   tp_rate  fp_rate   fn_rate       model
0  478  602  1551  1344  0.72039  0.737651  0.27961  0.262349  cv2cv4full

   Accuracy  F1 score  Precision    Recall       model
0  0.728302  0.713376   0.690647  0.737651  cv2cv4full

### 1.4 Averaging ensemble of models best at predicting target 0 only (cv2, cv3, full)

In [824]:
file_list = ['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv2.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv3.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.wholedata.hdf5.prediction.csv']
conf_matrix_cv2cv3full, performance_cv2cv3full = matrix_performance(test_df, file_list)
conf_matrix_cv2cv3full['model'] = ['cv2cv3full']
performance_cv2cv3full['model'] = ['cv2cv3full']
display(conf_matrix_cv2cv3full, performance_cv2cv3full)

    fn   fp    tn    tp  tn_rate   tp_rate  fp_rate   fn_rate       model
0  526  546  1607  1296   0.7464  0.711306   0.2536  0.288694  cv2cv3full

   Accuracy  F1 score  Precision    Recall       model
0  0.730314  0.707424   0.703583  0.711306  cv2cv3full

### 1.5 Averaging ensemble of models best at predicting target 0 only (cv3, full)

In [825]:
file_list = ['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv3.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.wholedata.hdf5.prediction.csv']
conf_matrix_cv3full, performance_cv3full = matrix_performance(test_df, file_list)
conf_matrix_cv3full['model'] = ['cv3full']
performance_cv3full['model'] = ['cv3full']
display(conf_matrix_cv3full, performance_cv3full)

    fn   fp    tn    tp   tn_rate   tp_rate   fp_rate   fn_rate    model
0  576  524  1629  1246  0.756619  0.683864  0.243381  0.316136  cv3full

   Accuracy  F1 score  Precision    Recall    model
0   0.72327  0.693764   0.703955  0.683864  cv3full

### 1.6 Averaging ensemble of models best at predicting target 1 only (cv1, cv0, cv4)

In [826]:
file_list = ['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv0.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv1.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv4.prediction.csv']
conf_matrix_cv0cv1cv4, performance_cv0cv1cv4 = matrix_performance(test_df, file_list)
conf_matrix_cv0cv1cv4['model'] = ['cv0cv1cv4']
performance_cv0cv1cv4['model'] = ['cv0cv1cv4']
display(conf_matrix_cv0cv1cv4, performance_cv0cv1cv4)

    fn   fp    tn    tp   tn_rate   tp_rate   fp_rate   fn_rate      model
0  416  685  1468  1406  0.681839  0.771679  0.318161  0.228321  cv0cv1cv4

   Accuracy  F1 score  Precision    Recall      model
0  0.723019   0.71863   0.672406  0.771679  cv0cv1cv4

### 1.7 Averaging ensemble of models best at predicting target 1 only (cv1, cv0)¶

In [827]:
file_list = ['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv0.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv1.prediction.csv']
conf_matrix_cv0cv1, performance_cv0cv1 = matrix_performance(test_df, file_list)
conf_matrix_cv0cv1['model'] = ['cv0cv1']
performance_cv0cv1['model'] = ['cv0cv1']
display(conf_matrix_cv0cv1, performance_cv0cv1)

    fn   fp    tn    tp   tn_rate   tp_rate   fp_rate   fn_rate   model
0  418  706  1447  1404  0.672085  0.770582  0.327915  0.229418  cv0cv1

   Accuracy  F1 score  Precision    Recall   model
0  0.717233   0.71414   0.665403  0.770582  cv0cv1

In [828]:
pd.concat([conf_matrix_table, 
          conf_matrix_all, conf_matrix_cv2cv4, conf_matrix_cv2cv4full,
          conf_matrix_cv2cv3full, conf_matrix_cv3full,
          conf_matrix_cv0cv1cv4, conf_matrix_cv0cv1])

    fn   fp    tn    tp   tn_rate   tp_rate   fp_rate   fn_rate       model
0  485  704  1449  1337  0.673014  0.733809  0.326986  0.266191         cv0
0  442  775  1378  1380  0.640037  0.757409  0.359963  0.242591         cv1
0  537  649  1504  1285  0.698560  0.705269  0.301440  0.294731         cv2
0  653  558  1595  1169  0.740827  0.641603  0.259173  0.358397         cv3
0  505  684  1469  1317  0.682304  0.722832  0.317696  0.277168         cv4
0  579  536  1617  1243  0.751045  0.682217  0.248955  0.317783       whole
0  440  606  1547  1382  0.718532  0.758507  0.281468  0.241493  all models
0  472  653  1500  1350  0.696702  0.740944  0.303298  0.259056      cv2cv4
0  478  602  1551  1344  0.720390  0.737651  0.279610  0.262349  cv2cv4full
0  526  546  1607  1296  0.746400  0.711306  0.253600  0.288694  cv2cv3full
0  576  524  1629  1246  0.756619  0.683864  0.243381  0.316136     cv3full
0  416  685  1468  1406  0.681839  0.771679  0.318161  0.228321   cv0cv1cv4
0  418  706  1447  1404  0.672085  0.770582  0.327915  0.229418      cv0cv1

In [829]:
pd.concat([performance_table, 
          performance_all, performance_cv2cv4, performance_cv2cv4full,
          performance_cv2cv3full, performance_cv3full,
          performance_cv0cv1cv4, performance_cv0cv1])

   Accuracy  F1 score  Precision    Recall       model
0  0.700881  0.692208   0.655071  0.733809         cv0
0  0.693836  0.693990   0.640371  0.757409         cv1
0  0.701635  0.684239   0.664426  0.705269         cv2
0  0.695346  0.658777   0.676896  0.641603         cv3
0  0.700881  0.688988   0.658171  0.722832         cv4
0  0.719497  0.690364   0.698707  0.682217       whole
0  0.736855  0.725459   0.695171  0.758507  all models
0  0.716981  0.705882   0.673989  0.740944      cv2cv4
0  0.728302  0.713376   0.690647  0.737651  cv2cv4full
0  0.730314  0.707424   0.703583  0.711306  cv2cv3full
0  0.723270  0.693764   0.703955  0.683864     cv3full
0  0.723019  0.718630   0.672406  0.771679   cv0cv1cv4
0  0.717233  0.714140   0.665403  0.770582      cv0cv1

### Conclusion of averaging ensemble

Above results showed that

1) The performance of all averaging ensemble models was better than that of single models.

2) In terms of accuracy, 'all models' yeild the best accuracy (73.7%), that is because it get on average both good tn_rate (71.9%) and good tp_rate (75.9%). However, this ensembled model is not best when predicting safety = 0 along and safety = 1 alone.

3) When predicting safety = 0, 'cv3full' yeild the best prediction (tn_rate 75.7%).

4) When predicting safety = 1, 'cv0cv1cv4' yeild the best prediction (tp_rate 77.2%).

## 2. Conditional ensemble
Next, we would try whether conditional ensemble could further boost the model performance.

In [888]:
# function that calculates conditional ensembling 
def cond_ensemble(test_df, file_list0, file_list1):
    
    #produce averaging ensembled model's prediction - 'averaged_prediction'
    df_list0 = []
    for f in file_list0:
        df = pd.read_csv(f)
        df = df.sort_values("_file")
        df_list0.append(df)
        
    prediction0 = pd.concat(df_list0).groupby('_file').mean()
    prediction0.reset_index(level=0, inplace=True)
    prediction0['pred_safety'] =  np.where(prediction0['0'] > 0.5, 0, 1)
    
    
    df_list1 = []
    for f in file_list1:
        df = pd.read_csv(f)
        df = df.sort_values("_file")
        df_list1.append(df)
        
    prediction1 = pd.concat(df_list1).groupby('_file').mean()
    prediction1.reset_index(level=0, inplace=True)
    prediction1['pred_safety'] =  np.where(prediction1['0'] > 0.5, 0, 1)
    
    
    pred = pd.merge(prediction0, prediction1, how='outer', on='_file')
    pred.columns = ['_file', 'pred0_0', 'pred0_1', 'pred0_pred_safety',  'pred1_0', 'pred1_1', 'pred1_pred_safety']

    return pred

In [886]:
# function that calculates each single model's confusion matrix and performance tables
def matrix_performance_cond_ensemble_model(test_df, data):
    
    #for a single model, no need to average
    prediction = data 
    
    #prepare y_true, y_pred
    df = pd.merge(test_df, prediction, how='left', on='_file', 
                   indicator=True)
    df[df['_merge'] == 'left_only']
    df = df[df['_merge'] == 'both']
    df['pred_safety'] = df['pred_safety'].astype(int)
    
    y_true = df['safety']
    y_pred = df['pred_safety']
    
    #confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    matrix = pd.DataFrame([{'tn': tn, 'fp': fp, 'fn': fn, 'tp': tp}])
    matrix['tn_rate'] = matrix['tn'] / (matrix['tn'] + matrix['fp'])
    matrix['tp_rate'] = matrix['tp'] / (matrix['fn'] + matrix['tp'])
    

    matrix['fp_rate'] = matrix['fp'] / (matrix['tn'] + matrix['fp'])
    matrix['fn_rate'] = matrix['fn'] / (matrix['fn'] + matrix['tp'])
    
    
    #performance
    accuracy = accuracy_score(y_true, y_pred) # accuracy: (tp + tn) / (p + n)
    precision = precision_score(y_true, y_pred) # precision tp / (tp + fp)
    recall = recall_score(y_true, y_pred) # recall: tp / (tp + fn)
    f1 = f1_score(y_true, y_pred) # f1: 2 tp / (2 tp + fp + fn)
    performance = pd.DataFrame([{'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 score': f1}])
    
    return matrix, performance

### 2.1 Conditional ensemble 1
When predicting safety = 0, we use the prediction by 'cv3full'; else we use the prediction by 'cv0cv1cv4'.

In [892]:
file_list0 = ['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv3.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.wholedata.hdf5.prediction.csv']


file_list1 = ['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv0.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv1.prediction.csv',
             '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv4.prediction.csv']

In [1051]:
pred = cond_ensemble(test_df, file_list0, file_list1)
#pred.head()
pred['pred_safety'] = np.where(pred['pred0_pred_safety'] == 0, 0, pred['pred1_pred_safety'])
conf_matrix_cond1, performance_cond1 = matrix_performance_cond_ensemble_model(test_df, pred)
conf_matrix_cond1['model'] = ['conditional ensemble1']
performance_cond1['model'] = ['conditional ensemble1']
display(conf_matrix_cond1, performance_cond1)

,fn,fp,tn,tp,tn_rate,tp_rate,fp_rate,fn_rate,model
0,664,439,1714,1158,0.796098,0.635565,0.203902,0.364435,conditional ensemble1

   Accuracy  F1 score  Precision    Recall                  model
0  0.722516  0.677391    0.72511  0.635565  conditional ensemble1

### Conditional ensemble 2
When predicting safety = 1, we use the prediction by 'cv0cv1cv4'; else we use the prediction by 'cv3full'.

In [929]:
pred = cond_ensemble(test_df, file_list0, file_list1)
pred.head()

,_file,pred0_0,pred0_1,pred0_pred_safety,pred1_0,pred1_1,pred1_pred_safety
0,gsv_0.jpg,0.001240,0.998759,1,0.067780,0.932220,1
1,gsv_1.jpg,0.625578,0.374422,0,0.300211,0.699789,1
2,gsv_10.jpg,0.000350,0.999650,1,0.042941,0.957059,1
3,gsv_100.jpg,0.588373,0.411627,0,0.391305,0.608695,1
4,gsv_1000.jpg,0.032821,0.967179,1,0.302465,0.697535,1

In [930]:
pred = cond_ensemble(test_df, file_list0, file_list1)
pred['pred_safety'] = np.where(pred['pred1_pred_safety'] == 1, 1, pred['pred0_pred_safety'])
conf_matrix_cond2, performance_cond2 = matrix_performance_cond_ensemble_model(test_df, pred)
conf_matrix_cond2['model'] = ['conditional ensemble2']
performance_cond2['model'] = ['conditional ensemble2']
display(conf_matrix_cond2, performance_cond2)

,fn,fp,tn,tp,tn_rate,tp_rate,fp_rate,fn_rate,model
0,328,770,1383,1494,0.642359,0.819978,0.357641,0.180022,conditional ensemble2

   Accuracy  F1 score  Precision    Recall                  model
0  0.723774  0.731278   0.659894  0.819978  conditional ensemble2

### Conclusion of conditional ensemble
Above results show that 'conditional ensemble 1' model is good at prediction target 0, at the expense of prediction 1.

On the contrary, 'conditional ensemble 2' model is good at prediction target 1, at the expense of prediction 0.

### 3. Weighted ensemble

### 3.1 Weighted ensemble 1

We give prediction by model 'cv3full' 0.4 weight; and prediction by model 'cv0cv1cv4' 0.6 weight.

In [938]:
pred = cond_ensemble(test_df, file_list0, file_list1)
pred['weight_pred_0'] = pred['pred0_0'] * 0.4 + pred['pred1_0'] * 0.6
pred['weight_pred_1'] = pred['pred0_1'] * 0.4 + pred['pred1_1'] * 0.6
pred['pred_safety'] =  np.where(pred['weight_pred_0'] > 0.5, 0, 1)
conf_matrix_w1, performance_w1 = matrix_performance_cond_ensemble_model(test_df, pred)
conf_matrix_w1['model'] = ['weighted ensemble1']
performance_w1['model'] = ['weighted ensemble1']
display(conf_matrix_w1, performance_w1)

,fn,fp,tn,tp,tn_rate,tp_rate,fp_rate,fn_rate,model
0,445,610,1543,1377,0.716674,0.755763,0.283326,0.244237,weighted ensemble1

   Accuracy  F1 score  Precision    Recall               model
0  0.734591  0.723024   0.693005  0.755763  weighted ensemble1

### 3.2 Weighted ensemble 2
We give prediction by model 'cv3full' 0.45 weight; and prediction by model 'cv0cv1cv4' 0.55 weight.

In [937]:
pred = cond_ensemble(test_df, file_list0, file_list1)
pred['weight_pred_0'] = pred['pred0_0'] * 0.45 + pred['pred1_0'] * 0.55
pred['weight_pred_1'] = pred['pred0_1'] * 0.45 + pred['pred1_1'] * 0.55
pred['pred_safety'] =  np.where(pred['weight_pred_0'] > 0.5, 0, 1)
conf_matrix_w2, performance_w2 = matrix_performance_cond_ensemble_model(test_df, pred)
conf_matrix_w2['model'] = ['weighted ensemble2']
performance_w2['model'] = ['weighted ensemble2']
display(conf_matrix_w2, performance_w2)

,fn,fp,tn,tp,tn_rate,tp_rate,fp_rate,fn_rate,model
0,457,597,1556,1365,0.722712,0.749177,0.277288,0.250823,weighted ensemble2

   Accuracy  F1 score  Precision    Recall               model
0  0.734843  0.721459   0.695719  0.749177  weighted ensemble2

### 3.3 Weighted ensemble 3
We give prediction by model 'cv3full' 0.55 weight; and prediction by model 'cv0cv1cv4' 0.45 weight.

In [936]:
pred = cond_ensemble(test_df, file_list0, file_list1)
pred['weight_pred_0'] = pred['pred0_0'] * 0.55 + pred['pred1_0'] * 0.45
pred['weight_pred_1'] = pred['pred0_1'] * 0.55 + pred['pred1_1'] * 0.45
pred['pred_safety'] =  np.where(pred['weight_pred_0'] > 0.5, 0, 1)
conf_matrix_w3, performance_w3 = matrix_performance_cond_ensemble_model(test_df, pred)
conf_matrix_w3['model'] = ['weighted ensemble3']
performance_w3['model'] = ['weighted ensemble3']
display(conf_matrix_w3, performance_w3)

,fn,fp,tn,tp,tn_rate,tp_rate,fp_rate,fn_rate,model
0,478,574,1579,1344,0.733395,0.737651,0.266605,0.262349,weighted ensemble3

   Accuracy  F1 score  Precision    Recall               model
0  0.735346  0.718717    0.70073  0.737651  weighted ensemble3

### 3.4 Weighted ensemble 4
We give prediction by model 'cv3full' 0.555 weight; and prediction by model 'cv0cv1cv4' 0.455 weight.

In [944]:
pred = cond_ensemble(test_df, file_list0, file_list1)
pred['weight_pred_0'] = pred['pred0_0'] * 0.555 + pred['pred1_0'] * 0.445
pred['weight_pred_1'] = pred['pred0_1'] * 0.555 + pred['pred1_1'] * 0.445
pred['pred_safety'] =  np.where(pred['weight_pred_0'] > 0.5, 0, 1)
conf_matrix_w4, performance_w4 = matrix_performance_cond_ensemble_model(test_df, pred)
conf_matrix_w4['model'] = ['weighted ensemble4']
performance_w4['model'] = ['weighted ensemble4']
display(conf_matrix_w4, performance_w4)

,fn,fp,tn,tp,tn_rate,tp_rate,fp_rate,fn_rate,model
0,480,572,1581,1342,0.734324,0.736553,0.265676,0.263447,weighted ensemble4

   Accuracy  F1 score  Precision    Recall               model
0  0.735346  0.718415   0.701149  0.736553  weighted ensemble4

### All results

In [945]:
pd.concat([conf_matrix_table, 
          conf_matrix_all, conf_matrix_cv2cv4, conf_matrix_cv2cv4full,
          conf_matrix_cv2cv3full, conf_matrix_cv3full,
          conf_matrix_cv0cv1cv4, conf_matrix_cv0cv1,
          conf_matrix_cond1, conf_matrix_cond2, conf_matrix_w1, conf_matrix_w2, conf_matrix_w3, conf_matrix_w4])

,fn,fp,tn,tp,tn_rate,tp_rate,fp_rate,fn_rate,model
0,485,704,1449,1337,0.673014,0.733809,0.326986,0.266191,cv0
0,442,775,1378,1380,0.640037,0.757409,0.359963,0.242591,cv1
0,537,649,1504,1285,0.698560,0.705269,0.301440,0.294731,cv2
0,653,558,1595,1169,0.740827,0.641603,0.259173,0.358397,cv3
0,505,684,1469,1317,0.682304,0.722832,0.317696,0.277168,cv4
0,579,536,1617,1243,0.751045,0.682217,0.248955,0.317783,whole
0,440,606,1547,1382,0.718532,0.758507,0.281468,0.241493,all models
0,472,653,1500,1350,0.696702,0.740944,0.303298,0.259056,cv2cv4
0,478,602,1551,1344,0.720390,0.737651,0.279610,0.262349,cv2cv4full
0,526,546,1607,1296,0.746400,0.711306,0.253600,0.288694,cv2cv3full
0,576,524,1629,1246,0.756619,0.683864,0.243381,0.316136,cv3full
0,416,685,1468,1406,0.681839,0.771679,0.318161,0.228321,cv0cv1cv4
0,418,706,1447,1404,0.672085,0.770582,0.327915,0.229418,cv0cv1
0,664,439,1714,1158,0.796098,0.635565,0.203902,0.364435,conditional ensemble1
0,328,770,1383,1494,0.642359,0.819978,0.357641,0.180022,conditional ensemble2
0,445,610,1543,1377,0.716674,0.755763,0.283326,0.244237,weighted ensemble1
0,457,597,1556,1365,0.722712,0.749177,0.277288,0.250823,weighted ensemble2
0,478,574,1579,1344,0.733395,0.737651,0.266605,0.262349,weighted ensemble3
0,480,572,1581,1342,0.734324,0.736553,0.265676,0.263447,weighted ensemble4

In [946]:
pd.concat([performance_table, 
          performance_all, performance_cv2cv4, performance_cv2cv4full,
          performance_cv2cv3full, performance_cv3full,
          performance_cv0cv1cv4, performance_cv0cv1,
          performance_cond1, performance_cond2, performance_w1, performance_w2, performance_w3, performance_w4])

   Accuracy  F1 score  Precision    Recall                  model
0  0.700881  0.692208   0.655071  0.733809                    cv0
0  0.693836  0.693990   0.640371  0.757409                    cv1
0  0.701635  0.684239   0.664426  0.705269                    cv2
0  0.695346  0.658777   0.676896  0.641603                    cv3
0  0.700881  0.688988   0.658171  0.722832                    cv4
0  0.719497  0.690364   0.698707  0.682217                  whole
0  0.736855  0.725459   0.695171  0.758507             all models
0  0.716981  0.705882   0.673989  0.740944                 cv2cv4
0  0.728302  0.713376   0.690647  0.737651             cv2cv4full
0  0.730314  0.707424   0.703583  0.711306             cv2cv3full
0  0.723270  0.693764   0.703955  0.683864                cv3full
0  0.723019  0.718630   0.672406  0.771679              cv0cv1cv4
0  0.717233  0.714140   0.665403  0.770582                 cv0cv1
0  0.722516  0.677391   0.725110  0.635565  conditional ensemble1
0  0.723774  0.731278   0.659894  0.819978  conditional ensemble2
0  0.734591  0.723024   0.693005  0.755763     weighted ensemble1
0  0.734843  0.721459   0.695719  0.749177     weighted ensemble2
0  0.735346  0.718717   0.700730  0.737651     weighted ensemble3
0  0.735346  0.718415   0.701149  0.736553     weighted ensemble4

### 4. Subdistrict conditional ensemble

### 4.1 Subdistrict conditional ensemble 1

In [994]:
test_csv = "/Users/zhanglingling/Desktop/ML1030/us_safety/boston_test_fetched_with_target.csv"  
test_df = pd.read_csv(test_csv)
test_df = test_df.sort_values("_file")
test_df = test_df[['_file', 'safety', 'SUBDISTRIC']]

predict_dir = '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/'
file_list = list(glob.glob(predict_dir + "*.csv*"))
file_list.sort()
file_list

['/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv0.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv1.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv2.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv3.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.hdf5.cv4.prediction.csv',
 '/Users/zhanglingling/Desktop/ML1030/boston_test_prediction/boston.test_bestmodel.wholedata.hdf5.prediction.csv']

In [995]:
df_list = []
for f in file_list:
    df = pd.read_csv(f)
    df = df.sort_values("_file")
    df_list.append(df)

In [1013]:
def subdistrict_conf_matrix(test_df, df):
    
    df['pred_safety'] =  np.where(df['0'] > 0.5, 0, 1)
    
    
    df = pd.merge(test_df, df, how='left', on='_file', 
                   indicator=True)
    df[df['_merge'] == 'left_only']
    df = df[df['_merge'] == 'both']
    df['pred_safety'] = df['pred_safety'].astype(int)

    # subdistrict count for all test data
    subdistrict_count_all = df.groupby(['SUBDISTRIC']).count()['_file']
    count_all = pd.DataFrame(subdistrict_count_all)
    count_all.reset_index(level=0, inplace=True)

    #tp
    subdistrict_count = df.loc[np.where((df['safety'] == 1) & (df['pred_safety']== 1))].groupby(['SUBDISTRIC']).count()['_file']
    tp_subdistrict = pd.DataFrame(subdistrict_count)
    tp_subdistrict.reset_index(level=0, inplace=True)
    tp_subdistrict.columns = ['SUBDISTRIC', 'tp']


    #tn
    subdistrict_count = df.loc[np.where((df['safety'] == 0) & (df['pred_safety']== 0))].groupby(['SUBDISTRIC']).count()['_file']
    tn_subdistrict = pd.DataFrame(subdistrict_count)
    tn_subdistrict.reset_index(level=0, inplace=True)
    tn_subdistrict.columns = ['SUBDISTRIC', 'tn']


    #fn
    subdistrict_count = df.loc[np.where((df['safety'] == 1) & (df['pred_safety']== 0))].groupby(['SUBDISTRIC']).count()['_file']
    fn_subdistrict = pd.DataFrame(subdistrict_count)
    fn_subdistrict.reset_index(level=0, inplace=True)
    fn_subdistrict.columns = ['SUBDISTRIC', 'fn']


    #fp
    subdistrict_count = df.loc[np.where((df['safety'] == 0) & (df['pred_safety']== 1))].groupby(['SUBDISTRIC']).count()['_file']
    fp_subdistrict = pd.DataFrame(subdistrict_count)
    fp_subdistrict.reset_index(level=0, inplace=True)
    fp_subdistrict.columns = ['SUBDISTRIC', 'fp']

    subdistrict = pd.merge(tp_subdistrict, tn_subdistrict, how='outer', on='SUBDISTRIC')
    subdistrict =  pd.merge(subdistrict, fn_subdistrict, how='outer', on='SUBDISTRIC')
    subdistrict =  pd.merge(subdistrict, fp_subdistrict, how='outer', on='SUBDISTRIC')


    # subdistrict count for all test data
    subdistrict_count_all = df.groupby(['SUBDISTRIC']).count()['_file']
    count_all = pd.DataFrame(subdistrict_count_all)
    count_all.columns = ['count_all']
    count_all.reset_index(level=0, inplace=True)


    #fp_subdistrict['fp_rate'] = fp_subdistrict['fp_count']
    subdistrict = pd.merge(subdistrict, count_all, how='right', on='SUBDISTRIC')

    subdistrict['accuracy'] = (subdistrict['tp'] + subdistrict['tn'])/ subdistrict['count_all']
    
    subdistrict['tp_rate'] = subdistrict['tp'] / subdistrict['count_all']
    subdistrict['tn_rate'] = subdistrict['tn'] / subdistrict['count_all']
    #subdistrict['fn_rate'] = subdistrict['fn'] / subdistrict['count_all']
    #subdistrict['fp_rate'] = subdistrict['fp'] / subdistrict['count_all']


    return subdistrict

In [1014]:
subdistrict_list = []
for i in range(len(df_list)):
    subdistrict = subdistrict_conf_matrix(test_df, df_list[i])
    subdistrict_list.append(subdistrict)
subdistrict_list[0]['model'] = 'cv0'
subdistrict_list[1]['model'] = 'cv1'
subdistrict_list[2]['model'] = 'cv2'
subdistrict_list[3]['model'] = 'cv3'
subdistrict_list[4]['model'] = 'cv4'
subdistrict_list[5]['model'] = 'full'

In [1017]:
pd.concat([subdistrict_list[0], subdistrict_list[1], subdistrict_list[2],
          subdistrict_list[3], subdistrict_list[4], subdistrict_list[5]]).sort_values(by = ['SUBDISTRIC', 'accuracy'])

,SUBDISTRIC,tp,tn,fn,fp,count_all,accuracy,tp_rate,tn_rate,model
0,Business,69,86,27,49,231,0.670996,0.298701,0.372294,cv1
0,Business,56,101,40,34,231,0.679654,0.242424,0.437229,cv3
0,Business,73,87,23,48,231,0.692641,0.316017,0.376623,cv4
0,Business,65,96,31,39,231,0.696970,0.281385,0.415584,cv2
0,Business,68,98,28,37,231,0.718615,0.294372,0.424242,cv0
0,Business,64,108,32,27,231,0.744589,0.277056,0.467532,full
1,Comm/Instit,30,26,10,20,86,0.651163,0.348837,0.302326,cv2
1,Comm/Instit,29,29,11,17,86,0.674419,0.337209,0.337209,cv1
1,Comm/Instit,30,31,10,15,86,0.709302,0.348837,0.360465,cv3
1,Comm/Instit,32,31,8,15,86,0.732558,0.372093,0.360465,cv0
1,Comm/Instit,33,33,7,13,86,0.767442,0.383721,0.383721,full
1,Comm/Instit,34,33,6,13,86,0.779070,0.395349,0.383721,cv4
2,Industrial,156,214,55,95,520,0.711538,0.300000,0.411538,cv1
2,Industrial,139,240,72,69,520,0.728846,0.267308,0.461538,full
2,Industrial,144,236,67,73,520,0.730769,0.276923,0.453846,cv2
2,Industrial,138,243,73,66,520,0.732692,0.265385,0.467308,cv3
2,Industrial,159,226,52,83,520,0.740385,0.305769,0.434615,cv0
2,Industrial,158,230,53,79,520,0.746154,0.303846,0.442308,cv4
3,Miscellaneous,52,61,29,28,170,0.664706,0.305882,0.358824,cv4
3,Miscellaneous,50,67,31,22,170,0.688235,0.294118,0.394118,cv3
3,Miscellaneous,55,65,26,24,170,0.705882,0.323529,0.382353,cv0
3,Miscellaneous,52,68,29,21,170,0.705882,0.305882,0.400000,full
3,Miscellaneous,60,62,21,27,170,0.717647,0.352941,0.364706,cv1
3,Miscellaneous,55,67,26,22,170,0.717647,0.323529,0.394118,cv2
4,Mixed Use,76,113,48,28,265,0.713208,0.286792,0.426415,cv3
4,Mixed Use,89,102,35,39,265,0.720755,0.335849,0.384906,cv2
4,Mixed Use,92,102,32,39,265,0.732075,0.347170,0.384906,cv0
4,Mixed Use,94,101,30,40,265,0.735849,0.354717,0.381132,cv1
4,Mixed Use,96,104,28,37,265,0.754717,0.362264,0.392453,cv4
4,Mixed Use,91,109,33,32,265,0.754717,0.343396,0.411321,full
5,Open Space,210,283,126,92,711,0.693390,0.295359,0.398031,cv3
5,Open Space,248,246,88,129,711,0.694796,0.348805,0.345992,cv0
5,Open Space,256,239,80,136,711,0.696203,0.360056,0.336146,cv1
5,Open Space,231,264,105,111,711,0.696203,0.324895,0.371308,cv2
5,Open Space,241,255,95,120,711,0.697609,0.338959,0.358650,cv4
5,Open Space,224,280,112,95,711,0.708861,0.315049,0.393812,full
6,Residential,716,646,218,411,1992,0.683735,0.359438,0.324297,cv1
6,Residential,663,699,271,358,1992,0.683735,0.332831,0.350904,cv4
6,Residential,683,681,251,376,1992,0.684739,0.342871,0.341867,cv0
6,Residential,609,757,325,300,1992,0.685743,0.305723,0.380020,cv3
6,Residential,671,713,263,344,1992,0.694779,0.336847,0.357932,cv2
6,Residential,640,779,294,278,1992,0.712349,0.321285,0.391064,full

In [ ]:
def cond_ensemble(test_df, file_list0, file_list1):
    
    #produce averaging ensembled model's prediction - 'averaged_prediction'
    df_list0 = []
    for f in file_list0:
        df = pd.read_csv(f)
        df = df.sort_values("_file")
        df_list0.append(df)
        
    prediction0 = pd.concat(df_list0).groupby('_file').mean()
    prediction0.reset_index(level=0, inplace=True)
    prediction0['pred_safety'] =  np.where(prediction0['0'] > 0.5, 0, 1)
    
    
    df_list1 = []
    for f in file_list1:
        df = pd.read_csv(f)
        df = df.sort_values("_file")
        df_list1.append(df)
        
    prediction1 = pd.concat(df_list1).groupby('_file').mean()
    prediction1.reset_index(level=0, inplace=True)
    prediction1['pred_safety'] =  np.where(prediction1['0'] > 0.5, 0, 1)
    
    
    pred = pd.merge(prediction0, prediction1, how='outer', on='_file')
    pred.columns = ['_file', 'pred0_0', 'pred0_1', 'pred0_pred_safety',  'pred1_0', 'pred1_1', 'pred1_pred_safety']

    return pred

In [1018]:
df.head()

          _file  safety   SUBDISTRIC         0         1  pred_safety _merge
0     gsv_0.jpg       1   Industrial  0.172792  0.827208            1   both
1     gsv_1.jpg       1    Mixed Use  0.001679  0.998321            1   both
2    gsv_10.jpg       0   Open Space  0.124760  0.875240            1   both
3   gsv_100.jpg       1  Residential  0.329768  0.670232            1   both
4  gsv_1000.jpg       1  Residential  0.000005  0.999995            1   both

In [1073]:
df_cv0 = df_list[0][['_file', '0',  'pred_safety']]
df_cv0.columns = ['_file', 'cv0_0', 'cv0_pred_safety']

df_cv1 = df_list[1][['_file', '0',  'pred_safety']]
df_cv1.columns = ['_file', 'cv1_0', 'cv1_pred_safety']

df_cv2 = df_list[2][['_file', '0',  'pred_safety']]
df_cv2.columns = ['_file', 'cv2_0', 'cv2_pred_safety']

df_cv3 = df_list[3][['_file', '0',  'pred_safety']]
df_cv3.columns = ['_file', 'cv3_0',  'cv3_pred_safety']

df_cv4 = df_list[4][['_file', '0', 'pred_safety']]
df_cv4.columns = ['_file', 'cv4_0', 'cv4_pred_safety']

df_full = df_list[5][['_file', '0', 'pred_safety']]
df_full.columns = ['_file', 'full_0', 'full_pred_safety']

In [1074]:
df = pd.merge(df_cv0, df_cv1, how='outer', on='_file')
df = pd.merge(df, df_cv2, how='outer', on='_file')
df = pd.merge(df, df_cv3, how='outer', on='_file')
df = pd.merge(df, df_cv4, how='outer', on='_file')
df = pd.merge(df, df_full, how='outer', on='_file')

In [1075]:
df = pd.merge(test_df, df, how='right', on='_file')
df.head(10)

,_file,safety,SUBDISTRIC,cv0_0,cv0_pred_safety,cv1_0,cv1_pred_safety,cv2_0,cv2_pred_safety,cv3_0,cv3_pred_safety,cv4_0,cv4_pred_safety,full_0,full_pred_safety
0,gsv_0.jpg,1,Industrial,0.172792,1,0.000897,1,0.001470,1,0.000010,1,0.029651,1,2.470684e-03,1
1,gsv_1.jpg,1,Mixed Use,0.001679,1,0.141600,1,0.489313,1,0.255481,1,0.757354,0,9.956748e-01,0
2,gsv_10.jpg,0,Open Space,0.124760,1,0.003538,1,0.002887,1,0.000699,1,0.000525,1,6.885519e-07,1
3,gsv_100.jpg,1,Residential,0.329768,1,0.838563,0,0.104049,1,0.564805,0,0.005583,1,6.119415e-01,0
4,gsv_1000.jpg,1,Residential,0.000005,1,0.001298,1,0.003349,1,0.000621,1,0.906091,0,6.502168e-02,1
5,gsv_1001.jpg,0,Residential,0.999497,0,0.998825,0,1.000000,0,1.000000,0,0.997662,0,9.999574e-01,0
6,gsv_1002.jpg,0,Residential,0.786304,0,0.101245,1,0.001166,1,0.135368,1,0.001162,1,1.138180e-01,1
7,gsv_1003.jpg,1,Residential,0.999889,0,0.917877,0,0.999985,0,0.995524,0,0.999337,0,7.822251e-01,0
8,gsv_1004.jpg,0,Industrial,0.986578,0,0.967329,0,0.999464,0,0.999999,0,0.999802,0,9.992079e-01,0
9,gsv_1005.jpg,0,Residential,1.000000,0,0.969467,0,1.000000,0,1.000000,0,1.000000,0,9.994709e-01,0

In [1104]:
df.loc[df['SUBDISTRIC'] == "Business", "pred_safety"] = df["full_pred_safety"]
#df.loc[df['SUBDISTRIC'] == "Business", "pred_safety"] = np.where((df.loc[df['SUBDISTRIC'] == "Business"]["full_0"] + df.loc[df['SUBDISTRIC'] == "Business"]["cv4_0"]) / 2 > 0.5, 0, 1)
df.loc[df['SUBDISTRIC'] == "Comm/Instit", "pred_safety"] = df["cv4_pred_safety"]

df.loc[df['SUBDISTRIC'] == "Industrial", "pred_safety"] = df["cv4_pred_safety"]
df.loc[df['SUBDISTRIC'] == "Miscellaneous", "pred_safety"] = df["cv1_pred_safety"]

df.loc[df['SUBDISTRIC'] == "Mixed Use", "pred_safety"] = df["cv4_pred_safety"]
df.loc[df['SUBDISTRIC'] == "Open Space", "pred_safety"] = df["cv1_pred_safety"]

df.loc[df['SUBDISTRIC'] == "Residential", "pred_safety"] = df["full_pred_safety"]
#df.loc[df['SUBDISTRIC'] == "Residential", "pred_safety"] = np.where((df.loc[df['SUBDISTRIC'] == "Residential"]["full_0"] + df.loc[df['SUBDISTRIC'] == "Residential"]["cv1_0"]) / 2 > 0.5, 0, 1)
df["pred_safety"] = df["pred_safety"].astype(int)

In [1102]:
def matrix_performance_cond_ensemble_model2(df):
    
    y_true = df['safety']
    y_pred = df['pred_safety']
    
    #confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    matrix = pd.DataFrame([{'tn': tn, 'fp': fp, 'fn': fn, 'tp': tp}])
    matrix['tn_rate'] = matrix['tn'] / (matrix['tn'] + matrix['fp'])
    matrix['tp_rate'] = matrix['tp'] / (matrix['fn'] + matrix['tp'])
    

    matrix['fp_rate'] = matrix['fp'] / (matrix['tn'] + matrix['fp'])
    matrix['fn_rate'] = matrix['fn'] / (matrix['fn'] + matrix['tp'])
    
    
    #performance
    accuracy = accuracy_score(y_true, y_pred) # accuracy: (tp + tn) / (p + n)
    precision = precision_score(y_true, y_pred) # precision tp / (tp + fp)
    recall = recall_score(y_true, y_pred) # recall: tp / (tp + fn)
    f1 = f1_score(y_true, y_pred) # f1: 2 tp / (2 tp + fp + fn)
    performance = pd.DataFrame([{'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 score': f1}])
    
    return matrix, performance

In [1103]:
conf_matrix_subdistrict_c1, performance_subdistrict_c1 = matrix_performance_cond_ensemble_model2(df)
display(conf_matrix_subdistrict_c1, performance_subdistrict_c1)

    fn   fp    tn    tp   tn_rate   tp_rate   fp_rate   fn_rate
0  527  614  1539  1295  0.714817  0.710757  0.285183  0.289243

   Accuracy  F1 score  Precision    Recall
0  0.712956  0.694184   0.678366  0.710757